
[cursor]
style.shape = "Block"
style.blinking = "Always"
vi_mode_style = "Underline"

[env]
TERM = "xterm-256color"

[font]
size = 18
#use_thin_strokes = false

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

#[font.debug]
#persistent_logging = false

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
#family = "ComicShannsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 100000
multiplier = 3

[terminal.shell]
program = "/usr/local/bin/tmux" # <- Set your path
args = ["new-session", "-A", "-D", "-s", "🏡 Home"]

[window]
decorations = "None"
dynamic_title = true
padding = { x = 3, y = 3 }
opacity = 0.9

[general]

live_config_reload = true
import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml",
]

